site_name: Miguel IAW
nav:
    - Principal: index.md
    - Practica 1.5: practica-1.5.md

theme:
  name: material  

  palette:
    # Modo claro
    - scheme: default
      primary: pink
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Modo oscuro
    - scheme: slate
      primary: cyan
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - header.autohide
    - navigation.footer

extra:
  language: eu
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mgsa2000
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/stratachan3




plugins:
  - offline

copyright: Copyright - 2025 Miguel strachan